param(
    [string]$OutputDir = "C:\Users\smnbn\OneDrive\Documents\New project\docs\generated_diagrams"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

$diagrams = @(
    @{
        Name = "01_overall_system_block_diagram"
        Title = "Overall System Block Diagram"
        Description = "Shows the full planned sensing and inference flow from the pipe rig to the ESP32 output."
        Mermaid = @'
flowchart LR
    A["Water Pipe / Leak Test Rig"] --> B["Sensors"]
    B --> B1["INMP441 Microphone"]
    B --> B2["BME680 / DHT11 Environmental Data"]
    B --> B3["MPU6050 Vibration / IMU"]
    B --> B4["HC-SR04 Distance / Ultrasonic"]

    B1 --> C["ESP32"]
    B2 --> C
    B3 --> C
    B4 --> C

    C --> D["Feature Extraction"]
    D --> E["TensorFlow Lite Model Inference"]
    E --> F["Leak / No Leak Decision"]
    F --> G["LED / Alert Output"]
    F --> H["Serial Monitor / Debug Data"]
'@
    },
    @{
        Name = "02_ai_ml_development_pipeline"
        Title = "AI/ML Development Pipeline"
        Description = "Shows the computer-side workflow from raw audio to ESP32 deployment."
        Mermaid = @'
flowchart LR
    A["Raw Leak / No-Leak Audio"] --> B["Manifest + Labels"]
    B --> C["Feature Extraction"]
    C --> D["Training Dataset"]
    D --> E["TensorFlow Model Training"]
    E --> F["Model Evaluation"]
    F --> G["TensorFlow Lite Export"]
    G --> H["Arduino C/C++ Conversion"]
    H --> I["ESP32 Deployment"]
'@
    },
    @{
        Name = "03_esp32_integration_flow"
        Title = "Current ESP32 Integration Flow"
        Description = "Shows how the trained model is exported and integrated into the Arduino project."
        Mermaid = @'
flowchart LR
    A["Trained Model on Computer"] --> B["Export to .tflite"]
    B --> C["Convert to leak_model_data.h / .cpp"]
    A --> D["Export scaler_params.h"]
    C --> E["Copy Files into Arduino Sketch Folder"]
    D --> E
    E --> F["Compile / Upload to ESP32"]
    F --> G["Run Inference on ESP32"]
    G --> H["LED Output + Serial Output"]
'@
    },
    @{
        Name = "04_midpoint_demo_setup"
        Title = "Current Midpoint Demo Setup"
        Description = "Shows the current demo configuration using prepared feature vectors and live DHT11 values."
        Mermaid = @'
flowchart LR
    A["Prepared Feature Vectors from Training Pipeline"] --> C["ESP32"]
    B["Live DHT11 Temperature / Humidity"] --> C
    C --> D["TensorFlow Lite Inference"]
    D --> E["Leak Probability Output"]
    E --> F["LED Blink"]
    E --> G["Serial Monitor Display"]
'@
    },
    @{
        Name = "05_future_realtime_leak_detection_flow"
        Title = "Future Real-Time Leak Detection Flow"
        Description = "Shows the final target flow using live microphone audio and on-device feature extraction."
        Mermaid = @'
flowchart LR
    A["Live Pipe Audio"] --> B["ESP32 Audio Sampling"]
    B --> C["Feature Extraction on ESP32"]
    C --> D["TensorFlow Lite Model"]
    D --> E["Leak Probability"]
    E --> F["LED / Alert"]
    E --> G["Serial Output / Logging"]
'@
    },
    @{
        Name = "06_project_progress_diagram"
        Title = "Current Project Progress Diagram"
        Description = "Shows the current status from pipeline build-out to the next step of collecting real microphone data."
        Mermaid = @'
flowchart TD
    A["AI/ML Pipeline Built"] --> B["Synthetic / Prepared Data Working"]
    B --> C["Model Export Working"]
    C --> D["ESP32 Inference Working"]
    D --> E["Midpoint Demo Ready"]
    E --> F["Next Step: Real Microphone Data"]
    F --> G["Retrain on Real Pipe Recordings"]
    G --> H["Final Real-Time Leak Detection"]
'@
    }
)

$packLines = @(
    "# Presentation Diagram Pack",
    "",
    'This folder was generated by `docs\generate_presentation_diagrams.ps1`.',
    "",
    "It includes Mermaid source files for each diagram plus this combined Markdown pack.",
    ""
)

foreach ($diagram in $diagrams) {
    $mmdPath = Join-Path $OutputDir ($diagram.Name + ".mmd")
    Set-Content -Path $mmdPath -Value $diagram.Mermaid.Trim() -Encoding UTF8

    $packLines += "## $($diagram.Title)"
    $packLines += ""
    $packLines += $diagram.Description
    $packLines += ""
    $packLines += '```mermaid'
    $packLines += $diagram.Mermaid.Trim()
    $packLines += '```'
    $packLines += ""
}

$packPath = Join-Path $OutputDir "presentation_diagram_pack.md"
Set-Content -Path $packPath -Value ($packLines -join "`r`n") -Encoding UTF8

$htmlLines = @(
    "<!doctype html>",
    "<html lang=`"en`">",
    "<head>",
    "  <meta charset=`"utf-8`" />",
    "  <meta name=`"viewport`" content=`"width=device-width, initial-scale=1`" />",
    "  <title>Presentation Diagram Pack</title>",
    "  <script type=`"module`">",
    "    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';",
    "    mermaid.initialize({ startOnLoad: true, theme: 'default' });",
    "  </script>",
    "  <style>",
    "    body { font-family: Arial, sans-serif; margin: 32px; line-height: 1.45; color: #1f2937; }",
    "    h1, h2 { color: #111827; }",
    "    section { margin-bottom: 48px; }",
    "    .mermaid { background: #ffffff; border: 1px solid #d1d5db; border-radius: 12px; padding: 16px; }",
    "    p { max-width: 900px; }",
    "  </style>",
    "</head>",
    "<body>",
    "  <h1>Presentation Diagram Pack</h1>",
    "  <p>Open this file in a browser to view all Mermaid diagrams in one place.</p>"
)

foreach ($diagram in $diagrams) {
    $htmlLines += "  <section>"
    $htmlLines += "    <h2>$($diagram.Title)</h2>"
    $htmlLines += "    <p>$($diagram.Description)</p>"
    $htmlLines += "    <pre class=`"mermaid`">"
    $htmlLines += $diagram.Mermaid.Trim()
    $htmlLines += "    </pre>"
    $htmlLines += "  </section>"
}

$htmlLines += "</body>"
$htmlLines += "</html>"

$htmlPath = Join-Path $OutputDir "presentation_diagram_pack.html"
Set-Content -Path $htmlPath -Value ($htmlLines -join "`r`n") -Encoding UTF8

Write-Host "Generated diagram files in: $OutputDir"
Get-ChildItem $OutputDir | Select-Object Name, Length
